### ISSUE TITLE
Load Url to profile icon not working 

### ISSUE THREAD

**Issue by esraagadrubikal** [felixsoares/BottomNavygation#3]
I'm trying to load a picture from an URL to the profile icon, but it doesn't work any help with that?

**Comment by felixsoares** [comment]
can you show the code? which version ?

**Comment by esraagadrubikal** [comment]
I'm using this version : compile 'com.github.felixsoares:BottomNavygation:1.8.6'
And here is my code:

bottomNavigationView.addItemNav(new ItemNav(this, R.drawable.default_profile_pic, R.drawable.default_profile_pic).isProfileItem().addProfileColorAtive(R.color.app_accent_color).addProfileColorInative(android.R.color.white));
bottomNavigationView.updateImageProfile("http://3-photos7.motorcar.com/used-2015-ferrari-458_spider--1769-16943585-1-1024.jpg");

**Comment by felixsoares** [comment]
sorry, has a new version, you can do that in compile 'com.github.felixsoares:BottomNavygation:1.8.10'
please, test and comment if works ...
(remember to put internet permission in AndroidManifest)

**Comment by esraagadrubikal** [comment]
Yeah, it works!
